# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/17roIlFv_36sPFsQZIXb9TSsy-Cwjwcx0

Suppose you are going to borrow some books from the library. After arriving at the library, you take books one by one and put them in a basket. When you finish selecting all your desired books, you go to the librarian's desk to borrow them. The librarian then collects all your necessary details. According to this scenario, create a Python program that uses a stack to keep track of all the books and a dictionary to store all the details of a person.

**sample Input 1:**
Enter your name: John Doe
Enter your age: 25
Enter your address: 123 Main Street, Cityville
Enter the books you want to borrow (type 'done' when finished):
Book name: Python Programming
Book name: Algorithms and Data Structures
Book name: done

**sample Output 1:**
Books borrowed:
Algorithms and Data Structures
Python Programming

Person's details:
Name: John Doe
Age: 25
Address: 123 Main Street, Cityville
"""

def is_empty(stack):
    return len(stack) == 0

def push(stack, item):
    stack.append(item)

def pop(stack):
    if not is_empty(stack):
        return stack.pop()

def borrow_books():
    books_stack = []
    details = {}

    # Gather person's details
    name = input("Enter your name: ")
    details["Name"] = name
    age = input("Enter your age: ")
    details["Age"] = age
    address = input("Enter your address: ")
    details["Address"] = address

    print("Enter the books you want to borrow (type 'done' when finished):")
    while True:
        book = input("Book name: ")
        if book.lower() == 'done':
            break
        push(books_stack, book)

    # Display borrowed books
    print("\nBooks borrowed:")
    while not is_empty(books_stack):
        print(pop(books_stack))

    # Display person's details
    print("\nPerson's details:")
    for key, value in details.items():
        print(key + ": " + value)


if __name__ == "__main__":
    borrow_books()

"""Suppose you are a teacher managing a class of students and their marks. You have the option to input marks for each student or check the marks of a particular student.

As a teacher, you can input marks for each student by selecting the respective student's name from the list provided. Then, you will be prompted to enter the mark for that student.

As a student, you can check your mark by entering your name.

**Sample input:**
Are You a teacher or student?
0. Exit
1. Teacher
2. Student

Enter your choice: 1

1. Mehedi Hasan
2. Amit Kumar
3. Al Amin
4. Motasem Billah Asik
5. Sadib

Select the student by entering the number: 3

Name: Al Amin
Id: 3
Enter Mark: 90

Are You a teacher or student?
0. Exit
1. Teacher
2. Student

Enter your choice: 2

Enter Your name: Al Amin
90

Are You a teacher or student?
0. Exit
1. Teacher
2. Student

Enter your choice: 0

Exiting...

"""

print("Are You teacher or student?")
print("""
0. Exit
1. Teacher
2. Student
""")
students = ["Mehedi Hasan", "Amit Kumar", "Al Amin", "Motasem Billah Asik", "Sadib"]
marks = [
    {"name": "mehedi", "mark": 0},
    {"name": "amit", "mark": 0},
    {"name": "alamin", "mark": 0},
    {"name": "asik", "mark": 0},
    {"name": "sadib", "mark": 0}
]
while True:
    user = input()
    if user == '0':
        break
    elif user == '1':
        for index, student in enumerate(students, 1):
            print(f"{index}. {student}")
        studentName = int(input())
        if studentName == 1:
            print("Name: Mehedi Hasan")
            print("Id: 1")
            mehedi = int(input("Enter Mark:"))
            marks[0]["mark"] = mehedi
        elif studentName == 2:
            print("Name: Amit Kumar")
            print("Id: 2")
            amit = int(input("Enter Mark:"))
            marks[1]["mark"] = amit
        elif studentName == 3:
            print("Name: Al Amin")
            print("Id: 3")
            alamin = int(input("Enter Mark:"))
            marks[2]["mark"] = alamin
        elif studentName == 4:
            print("Name: Motasem Billah Asik")
            print("Id: 4")
            asik = int(input("Enter Mark:"))
            marks[3]["mark"] = asik
        elif studentName == 5:
            print("Name: Sadib")
            print("Id: 5")
            sadib = int(input("Enter Mark:"))
            marks[4]["mark"] = sadib
    elif user == '2':
        name = input("Enter Your name: ")
        for mark in marks:
            if mark["name"] == name:
                print(mark["mark"])
                break
    else:
        print("Enter valid input!")